/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;


import javax.swing.JOptionPane;
import Functions.*;
import Login.UserLogin;

/**
 *
 * @author Enzo
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form test
     */
    public Menu() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Opsi_CatatanServisRutin = new javax.swing.JButton();
        Opsi_HistoryService = new javax.swing.JButton();
        Opsi_DataKendaraan = new javax.swing.JButton();
        Opsi_ServiceExpenses = new javax.swing.JButton();
        Logout = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Autocare 1.0");
        setBackground(new java.awt.Color(255, 255, 255));
        setLocation(new java.awt.Point(400, 200));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 153, 0));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setBackground(new java.awt.Color(153, 153, 255));
        jLabel1.setFont(new java.awt.Font("OCR A Extended", 1, 36)); // NOI18N
        jLabel1.setText("Autocare v1.0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(357, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(357, 357, 357))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, -1));

        Opsi_CatatanServisRutin.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Opsi_CatatanServisRutin.setText("Service Record");
        Opsi_CatatanServisRutin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Opsi_CatatanServisRutinActionPerformed(evt);
            }
        });
        getContentPane().add(Opsi_CatatanServisRutin, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 195, 216, 55));

        Opsi_HistoryService.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Opsi_HistoryService.setText("History Service");
        Opsi_HistoryService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Opsi_HistoryServiceActionPerformed(evt);
            }
        });
        getContentPane().add(Opsi_HistoryService, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 285, 216, 55));

        Opsi_DataKendaraan.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Opsi_DataKendaraan.setText("Vehicle Data");
        Opsi_DataKendaraan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Opsi_DataKendaraanActionPerformed(evt);
            }
        });
        getContentPane().add(Opsi_DataKendaraan, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 105, 216, 55));

        Opsi_ServiceExpenses.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Opsi_ServiceExpenses.setText("Service Bills");
        Opsi_ServiceExpenses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Opsi_ServiceExpensesActionPerformed(evt);
            }
        });
        getContentPane().add(Opsi_ServiceExpenses, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 375, 216, 55));

        Logout.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        Logout.setForeground(new java.awt.Color(204, 0, 0));
        Logout.setText("Sign Out");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        getContentPane().add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 485, 108, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gears2_1.png"))); // NOI18N
        jLabel2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel2PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 600, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Opsi_CatatanServisRutinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Opsi_CatatanServisRutinActionPerformed
        dispose();
        ServiceRecord s = new ServiceRecord();
        s.setVisible(true);
    }//GEN-LAST:event_Opsi_CatatanServisRutinActionPerformed

    private void Opsi_HistoryServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Opsi_HistoryServiceActionPerformed
        dispose();
        RepairHistoryService s = new RepairHistoryService();
        s.setVisible(true);      
    }//GEN-LAST:event_Opsi_HistoryServiceActionPerformed

    private void Opsi_DataKendaraanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Opsi_DataKendaraanActionPerformed
    dispose();
    VehicleData s = new VehicleData();
    s.setVisible(true);        
    }//GEN-LAST:event_Opsi_DataKendaraanActionPerformed

    private void Opsi_ServiceExpensesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Opsi_ServiceExpensesActionPerformed
    dispose();
    ExpenseService s = new ExpenseService();
    s.setVisible(true);   
    }//GEN-LAST:event_Opsi_ServiceExpensesActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
    dispose();
    UserLogin s = new UserLogin();
    s.setVisible(true);     
    }//GEN-LAST:event_LogoutActionPerformed

    private void jLabel2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel2PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2PropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Logout;
    private javax.swing.JButton Opsi_CatatanServisRutin;
    private javax.swing.JButton Opsi_DataKendaraan;
    private javax.swing.JButton Opsi_HistoryService;
    private javax.swing.JButton Opsi_ServiceExpenses;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
