/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Functions;

import Main.Menu;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import net.proteanit.sql.DbUtils;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;

import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.stream.Stream;

/**
 *
 * @author bebas
 */
public class ExpenseService extends javax.swing.JFrame {
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    private String Kendaraanid;
    private String tmp;
    private String tmp2;
    private String KendaraanModel;
    /**
     * Creates new form ExpenseService
     */
    public ExpenseService() {
        initComponents();
        conn = DatabaseConnection.getConnection();
        setLocationRelativeTo(null);
        Fillcombo1();
        Updatetable();
    }
    
    
    public double getTotalServiceCost(String Kendaraanid) throws SQLException {
        try{
            String sql = "SELECT SUM(harga) AS totalCost FROM service WHERE vehicle_id = ?";
            pst = conn.prepareStatement(sql);
            pst.setString(1, Kendaraanid);;
            rs = pst.executeQuery();
                if (rs.next()) {
                    return rs.getDouble("totalCost");
                }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        return 0.0;
    }
    
    private void Fillcombo1(){
        try{
            String sql = "select * from vehicle";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            
            while(rs.next()){
                String id_vehicle = rs.getString("id");
                VehicleChooser.addItem(id_vehicle);
            }
        }catch(Exception e){
            
        }
    }

        private void Updatetable(){
        String tmp = (String)VehicleChooser.getSelectedItem();
        Kendaraanid = tmp;
        
        try{
            String sql = "select * from service where vehicle_id = ?"; 
            pst = conn.prepareStatement(sql);
            pst.setString(1, Kendaraanid);
            rs = pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Back = new javax.swing.JToggleButton();
        VehicleChooser = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        ServiceBillLabel = new javax.swing.JLabel();
        PrintBillButton = new javax.swing.JButton();
        PoliceIDLabel = new javax.swing.JLabel();
        Model = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Autocare 1.0 | Service Bills");
        setLocation(new java.awt.Point(400, 200));

        Back.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        VehicleChooser.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        VehicleChooser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose a vehicle" }));
        VehicleChooser.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                VehicleChooserPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        VehicleChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VehicleChooserActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(195, 44));

        ServiceBillLabel.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        ServiceBillLabel.setForeground(new java.awt.Color(255, 255, 255));
        ServiceBillLabel.setText("Service Bills");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(ServiceBillLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(ServiceBillLabel)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        PrintBillButton.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        PrintBillButton.setText("Print Bill");
        PrintBillButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintBillButtonActionPerformed(evt);
            }
        });

        PoliceIDLabel.setFont(new java.awt.Font("OCR A Extended", 2, 18)); // NOI18N

        Model.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(VehicleChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(PrintBillButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Model)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PoliceIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(134, 134, 134))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Back)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PoliceIDLabel)
                            .addComponent(Model))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VehicleChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PrintBillButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        dispose();
        Menu s = new Menu();
        s.setVisible(true);
        
    }//GEN-LAST:event_BackActionPerformed

    private void VehicleChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VehicleChooserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VehicleChooserActionPerformed

    private void PrintBillButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintBillButtonActionPerformed
    String tmp = (String)VehicleChooser.getSelectedItem();
    Kendaraanid = tmp;
//    String tmp2 = (String)Model.getSelectedItem();
    
    try {
        // Calculate total service cost
        double totalCost = getTotalServiceCost(Kendaraanid);

        // Generate PDF report
        Document document = new Document();
        PdfWriter.getInstance(document, new FileOutputStream("ServiceReport_Vehicle_" + Kendaraanid + ".pdf"));
        document.open();

        // Add title
        Paragraph title = new Paragraph("Service Report for Vehicle ID: |" + Kendaraanid +"| "+Model.getText());
        title.setAlignment(Element.ALIGN_CENTER);
        document.add(title);

        // Add table
        PdfPTable table = new PdfPTable(5);
        addTableHeader(table);
        addRows(table, Kendaraanid);
        document.add(table);

        // Add total cost
        Paragraph total = new Paragraph("Total Cost: Rp." + totalCost);
        total.setAlignment(Element.ALIGN_RIGHT);
        document.add(total);

        document.close();

        JOptionPane.showMessageDialog(null, "PDF report generated successfully!");

    } catch (DocumentException | IOException | SQLException ex) {
        JOptionPane.showMessageDialog(null, "Error generating PDF: " + ex.getMessage());
    }
    }//GEN-LAST:event_PrintBillButtonActionPerformed

private void addTableHeader(PdfPTable table) {
            Stream.of("ID", "Tanggal Servis", "Catatan", "Jenis Servis", "Harga")
          .forEach(columnTitle -> {
              PdfPCell header = new PdfPCell();
              header.setPhrase(new Paragraph(columnTitle));
              table.addCell(header);
          });
}

private void addRows(PdfPTable table, String Kendaraanid) throws SQLException {
    String sql = "SELECT id, tanggalServis, catatanTambahan, jenisServis, harga FROM service WHERE vehicle_id = ?";
    try{
        conn=(java.sql.Connection)Functions.DatabaseConnection.getConnection();
        pst=conn.prepareStatement(sql);
    
        pst.setString(1,Kendaraanid);
        rs = pst.executeQuery();
            while (rs.next()) {
                table.addCell(String.valueOf(rs.getInt("id")));
                table.addCell(rs.getString("tanggalServis"));
                table.addCell(rs.getString("catatanTambahan"));
                table.addCell(rs.getString("jenisServis"));
                table.addCell(String.valueOf(rs.getDouble("harga")));
            }
        
    }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Data not found");
        }        // TODO add your handling code here:
    }          
    
    private void VehicleChooserPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_VehicleChooserPopupMenuWillBecomeInvisible
        String tmp = (String)VehicleChooser.getSelectedItem();
        String sql = "select * from vehicle where id = ?";
        Kendaraanid = tmp;
        try{
            conn=(java.sql.Connection)Functions.DatabaseConnection.getConnection();
            pst=conn.prepareStatement(sql);
            pst.setString(1,tmp);
            rs = pst.executeQuery();
            if(rs.next()){
                String add1 = rs.getString("nomorPolisi");
                String add2 = rs.getString("model");
                PoliceIDLabel.setText(add1);
                Model.setText(add2 +" |");
            }
           Updatetable();

        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Data not found");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_VehicleChooserPopupMenuWillBecomeInvisible

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExpenseService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExpenseService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExpenseService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExpenseService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExpenseService().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Back;
    private javax.swing.JLabel Model;
    private javax.swing.JLabel PoliceIDLabel;
    private javax.swing.JButton PrintBillButton;
    private javax.swing.JLabel ServiceBillLabel;
    private javax.swing.JComboBox<String> VehicleChooser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private static class SQLException extends Exception {

        public SQLException() {
        }
    }
}
